Command failed: spleeter separate -o "D:\MyFiles\Coding\Ableton_Devices\AbleSpleeter" -p spleeter:5stems-16kHz "C:/Users/Sony/Documents/Ableton/Live Recordings/2022-11-30 071446 Temp Project/Samples/Processed/Crop/Ritviz & Nucleya - Roz [Official Audio] [2022-11-30 075225].wav"
Traceback (most recent call last):
  File "C:\Users\Sony\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Sony\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Sony\AppData\Local\Programs\Python\Python310\Scripts\spleeter.exe\__main__.py", line 7, in <module>
  File "C:\Users\Sony\AppData\Local\Programs\Python\Python310\lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "C:\Users\Sony\AppData\Local\Programs\Python\Python310\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\Sony\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Sony\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Sony\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Sony\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Sony\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Sony\AppData\Local\Programs\Python\Python310\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\Sony\AppData\Local\Programs\Python\Python310\lib\site-packages\spleeter\__main__.py", line 128, in separate
    separator.separate_to_file(
  File "C:\Users\Sony\AppData\Local\Programs\Python\Python310\lib\site-packages\spleeter\separator.py", line 378, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "C:\Users\Sony\AppData\Local\Programs\Python\Python310\lib\site-packages\spleeter\separator.py", line 321, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "C:\Users\Sony\AppData\Local\Programs\Python\Python310\lib\site-packages\spleeter\separator.py", line 265, in _separate_librosa
    sess = self._get_session()
  File "C:\Users\Sony\AppData\Local\Programs\Python\Python310\lib\site-packages\spleeter\separator.py", line 240, in _get_session
    saver.restore(self._session, latest_checkpoint)
  File "C:\Users\Sony\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\training\saver.py", line 1405, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.
